DROP TABLE IF EXISTS ELEMENTO_PROVEEDOR;

DROP TABLE IF EXISTS PROVEEDOR;

DROP TABLE IF EXISTS INSTALACION;

DROP TABLE IF EXISTS TECNICO;

DROP TABLE IF EXISTS SOLICITUD_SEDE;

DROP TABLE IF EXISTS SEDE;

DROP TABLE IF EXISTS SOLICITUD;

DROP TABLE IF EXISTS ELEMENTO;

DROP TABLE IF EXISTS USUARIO;

DROP TABLE IF EXISTS ROL;

DROP TABLE IF EXISTS STOCK;

DROP TABLE IF EXISTS CATEGORIA;

CREATE TABLE ROL
  (
     ID_ROL     INT (7) PRIMARY KEY,
     NOMBRE_ROL VARCHAR (15) NOT NULL
  );

CREATE TABLE USUARIO
  (
     ID_USUARIO       INT (7) PRIMARY KEY,
     ID_ROL           INT (7),
     NOMBRE_USUARIO   VARCHAR (50) NOT NULL,
     APELLIDO_USUARIO VARCHAR (30) NOT NULL,
     CONSTRAINT FK_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
  );

CREATE TABLE CATEGORIA
  (
     ID_CATEGORIA     INT (7) PRIMARY KEY,
     NOMBRE_CATEGORIA VARCHAR (50) NOT NULL
  );

CREATE TABLE ELEMENTO
  (
     ID_ELEMENTO     INT (10) PRIMARY KEY,
     ID_CATEGORIA    INT (7),
     SERIAL_ELEMENTO VARCHAR (50) NOT NULL,
     NOMBRE_ELEMENTO VARCHAR (30) NOT NULL,
     ESTADO_ELEMENTO VARCHAR (30) NOT NULL,
     CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(
     ID_CATEGORIA)
  );

CREATE TABLE SOLICITUD
  (
     ID_SOLICITUD          INT (10) PRIMARY KEY,
     ID_USUARIO            INT (7),
     ID_ELEMENTO           INT (10),
     INFORMACION_SOLICITUD VARCHAR (90) NOT NULL,
     FECHA_SOLICITUD       DATE NOT NULL,
     CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(
     ID_USUARIO),
     CONSTRAINT FK_ELEMENTO FOREIGN KEY (ID_ELEMENTO) REFERENCES ELEMENTO(
     ID_ELEMENTO)
  );

CREATE TABLE SEDE
  (
     ID_SEDE                INT (10) PRIMARY KEY,
     DIRECCION_SEDE         VARCHAR (30) NOT NULL,
     TIPO_SEDE              VARCHAR (30) NOT NULL,
     ANALISTA_REGIONAL_SEDE VARCHAR (50) NOT NULL,
     CONTACTO_SEDE          VARCHAR (30) NOT NULL
  );

CREATE TABLE SOLICITUD_SEDE
  (
     ID_SOLICITUD_SEDE INT (7) PRIMARY KEY,
     ID_SEDE           INT (10),
     ID_SOLICITUD      INT (10),
     CONSTRAINT FK_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(
     ID_SOLICITUD),
     CONSTRAINT FK_SEDE FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE)
  );

CREATE TABLE TECNICO
  (
     ID_TECNICO             INT (10) PRIMARY KEY,
     IDENTIFICACION_TECNICO INT (30) NOT NULL,
     NOMBRE_TECNICO         VARCHAR (50) NOT NULL,
     EMPRESA_TECNICO        VARCHAR (20) NOT NULL,
     INSTALACION            INT (10) NOT NULL
  );

CREATE TABLE INSTALACION
  (
     ID_SOLICITUD       INT (10),
     ID_INSTALACION     INT (10) PRIMARY KEY,
     ID_TECNICO         INT (10),
     FECHA_INSTALACION  VARCHAR(10) NOT NULL,
     ESTADO_INSTALACION VARCHAR(30) NOT NULL,
     CONSTRAINT FK_SOLICITUD2 FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(
     ID_SOLICITUD),
     CONSTRAINT FK_TECNICO FOREIGN KEY (ID_TECNICO) REFERENCES TECNICO(
     ID_TECNICO)
  );

CREATE TABLE STOCK
  (
     ID_STOCK       INT (10) PRIMARY KEY,
     ID_CATEGORIA   INT (7),
     CANTIDAD_STOCK INT (10) NOT NULL,
     FECHA_STOCK    DATE NOT NULL,
     CONSTRAINT FK_CATEGORIA2 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(
     ID_CATEGORIA)
  );

CREATE TABLE PROVEEDOR
  (
     ID_PROVEEDOR       INT (10) PRIMARY KEY,
     NOMBRE_PROVEEDOR   VARCHAR (30) NOT NULL,
     TELEFONO_PROVEEDOR VARCHAR (30) NOT NULL,
     CORREO_PROVEEDOR   VARCHAR (50) NOT NULL
  );

CREATE TABLE ELEMENTO_PROVEEDOR
  (
     ID_PROVEEDOR INT (10),
     ID_ELEMENTO  INT (10),
     CONSTRAINT FK_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(
     ID_PROVEEDOR),
     CONSTRAINT FK_ELEMENTO2 FOREIGN KEY (ID_ELEMENTO) REFERENCES ELEMENTO(
     ID_ELEMENTO)
  );
